"use client";

import { HeroSection } from "@/components/hero-section";
import { AboutSection } from "@/components/about-section";
import { ProjectCard } from "@/components/project-card";
import { motion } from "framer-motion";
import { ParallaxDiv } from "@/components/parallaxDiv";

export default function HomePage() {
  const projects = [
    {
      title: "Federated Sentiment Analysis",
      description:
        "A sentiment analysis tool for social media using Apache Kafka to handle real-time data streams.",
      details: [
        "Developed a real-time sentiment analysis system using live Reddit data.",
      "Integrated Apache Kafka and Apache Flink for distributed data processing.",
      "Containerized and deployed on Google Cloud Platform using Docker for scalability."
      ],
      tech: ["Python", "Apache Kafka", "Apache Flink", "Docker", "Google Cloud Platform"]
    },
    {
      title: "Understanding V in Multi-Modal Language Models",
      description:
        "A research project exploring the visual capabilities of multi-modal language models.",
      details: [
        "Analyzed the visual understanding of multi-modal Language Models.",
        "Trained a visual language model using BERT and BEiT architectures.",
        "Created a custom dataset using COCO dataset and question and answer pairs generated by GPT-4.1",
        "Evaluated model performance on VQA task.",
      ],
      tech: ["Python", "PyTorch", "GPT-4.1"]
    },
    {
      title: "Debiasing the TextVQA Dataset",
      description:
        "A project focused on reducing biases in the TextVQA dataset to improve model fairness and accuracy.",
      details: [
      "Developed a debiasing framework to improve fairness and robustness in TextVQA.",
      "Integrated external datasets for enhanced bias reduction and generalization.",
      "Used the VQA dataset as normalization reference to mitigate dataset-specific bias."
      ], 
      tech: ["Python", "PyTorch", "Computer Vision"]
    },
  ];

  return (
    <main className="flex flex-col items-center justify-center overflow-hidden">
      <HeroSection />
      <AboutSection />

      {/* Projects Section */}
      <section className="relative py-20 px-6 text-center w-full">
        <motion.h2
          className="text-4xl md:text-6xl font-bold mb-12 bg-gradient-to-r from-purple-500 to-blue-500 bg-clip-text text-transparent"
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 1 }}
        >
          Featured Projects
        </motion.h2>

        <div className="grid md:grid-cols-3 gap-10 max-w-6xl mx-auto">
          {projects.map((project, index) => (
            <ProjectCard
              key={index}
              title={project.title}
              description={project.description}
              details={project.details}
              tech={project.tech}
            />
          ))}
        </div>

        {/* Background Parallax Glow */}
        <ParallaxDiv
          offset={120}
          className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top,rgba(168,85,247,0.1)_0%,transparent_70%)]"
        />
      </section>
    </main>
  );
}
